#include "PlayLevel.h"
#include "BackGround.h"

void PlayLevel::SetLevelData()
{
	//스테이지별로 차이점 세팅
	static int Stage = 0;
	Stage++;
	StageLevel =  Stage;

	std::vector<TTYPE> TileStartData;
	std::vector<OTYPE> TrapStartData;
	switch (Stage)
	{
	case 1:
		BackGroundPtr = CreateActor<BackGround>();
		BackGroundPtr->Init("chapterBG0001.bmp");

		TileStartData =
		{
			TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::KE, TTYPE::PL, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::UN, TTYPE::LO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::NO, TTYPE::UN, TTYPE::NO, TTYPE::UN, TTYPE::WA, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::NP, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,	TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
		};
		TrapStartData =
		{
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, 
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, 
			OTYPE::NO, 	OTYPE::NO, OTYPE::SP, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::SO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, 
			OTYPE::NO, 	OTYPE::NO, OTYPE::SF, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, 
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, 
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, 
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, 
		};
		TileMapStartData.Init(TileStartData, TrapStartData,{ 9.0f,8.0f }, { 510.0f,120.0f });
		break;
	case 2:
		BackGroundPtr = CreateActor<BackGround>();
		BackGroundPtr->Init("chapterBG0002.png");

		TileStartData =
		{
			TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, 
			TTYPE::WA, TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::NO, TTYPE::NO, TTYPE::WA, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::UN, TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::NO, TTYPE::NO, TTYPE::WA,
			TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::WA, TTYPE::WA, TTYPE::RO, TTYPE::RO, TTYPE::RO, TTYPE::WA,
			TTYPE::WA, TTYPE::PL, TTYPE::NO, TTYPE::WA, TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::NO, TTYPE::WA,
			TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::WA, TTYPE::WA, TTYPE::NO, TTYPE::UN, TTYPE::NO, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::NP, TTYPE::NO, TTYPE::UN, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, 
		};
		TrapStartData =
		{
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::SP, OTYPE::SP, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::SP, OTYPE::NO, OTYPE::NO, OTYPE::SP, OTYPE::SP, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::SP, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
		};
		TileMapStartData.Init(TileStartData, TrapStartData, { 9.0f,8.0f }, { 510.0f,120.0f });
		break;
	case 3:
		BackGroundPtr = CreateActor<BackGround>();
		BackGroundPtr->Init("chapterBG0003.png");

		TileStartData =
		{
			TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::KE, TTYPE::PL, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::UN, TTYPE::LO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::NO, TTYPE::UN, TTYPE::NO, TTYPE::UN, TTYPE::WA, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
			TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::NP, TTYPE::WA,
			TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,	TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
		};

		TrapStartData =
		{
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
			OTYPE::NO, 	OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO, OTYPE::NO,
		};
		TileMapStartData.Init(TileStartData, TrapStartData, { 9.0f,8.0f }, { 510.0f,120.0f });
		break;
	//case 4:
	//	BackGroundPtr = CreateActor<BackGround>();
	//	BackGroundPtr->Init("chapterBG0004.png");

	//	TileStartData =
	//	{
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::KE, TTYPE::PL, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::UN, TTYPE::LO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::NO, TTYPE::UN, TTYPE::NO, TTYPE::UN, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::NO, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::NP, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,	TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//	};
	//	TileMapStartData.Init(TileStartData, { 9.0f,8.0f }, { 510.0f,120.0f });
	//	break;
	//case 5:
	//	BackGroundPtr = CreateActor<BackGround>();
	//	BackGroundPtr->Init("chapterBG0005.png");

	//	TileStartData =
	//	{
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::KE, TTYPE::PL, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::SP, TTYPE::NO, TTYPE::UN, TTYPE::LO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::SO, TTYPE::UN, TTYPE::NO, TTYPE::UN, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::SF, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::NP, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,	TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//	};
	//	TileMapStartData.Init(TileStartData, { 9.0f,8.0f }, { 510.0f,120.0f });
	//	break;
	//case 6:
	//	BackGroundPtr = CreateActor<BackGround>();
	//	BackGroundPtr->Init("chapterBG0006.png");

	//	TileStartData =
	//	{
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::KE, TTYPE::PL, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::SP, TTYPE::NO, TTYPE::UN, TTYPE::LO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::SO, TTYPE::UN, TTYPE::NO, TTYPE::UN, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::SF, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::NP, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,	TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//	};
	//	TileMapStartData.Init(TileStartData, { 9.0f,8.0f }, { 510.0f,120.0f });

	//	break;
	//case 7:
	//	BackGroundPtr = CreateActor<BackGround>();
	//	BackGroundPtr->Init("chapterBG0007.png");

	//	TileStartData =
	//	{
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::KE, TTYPE::PL, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::SP, TTYPE::NO, TTYPE::UN, TTYPE::LO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::SO, TTYPE::UN, TTYPE::NO, TTYPE::UN, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::SF, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::NP, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,	TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//	};
	//	TileMapStartData.Init(TileStartData, { 9.0f,8.0f }, { 510.0f,120.0f });
	//	break;
	//case 8:
	//	BackGroundPtr = CreateActor<BackGround>();
	//	BackGroundPtr->Init("chapterBG0008.png");

	//	TileStartData =
	//	{
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::KE, TTYPE::PL, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::SP, TTYPE::NO, TTYPE::UN, TTYPE::LO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::SO, TTYPE::UN, TTYPE::NO, TTYPE::UN, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::SF, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::WA, TTYPE::WA,
	//		TTYPE::WA, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::RO, TTYPE::NO, TTYPE::NO, TTYPE::NP, TTYPE::WA,
	//		TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,	TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA, TTYPE::WA,
	//	};
	//	TileMapStartData.Init(TileStartData, { 9.0f,8.0f }, { 510.0f,120.0f }); 
	//	break;
	default:
		break;
	}
	

}

